### ISSUE TITLE
详细按钮可以优化

### ISSUE THREAD

**Issue by cyb233** [knowsex/knowsex.github.io#3]
详细按钮点击前后，详细内容中的分割线容易被忽略，并不能明确感受到是否已经点击过按钮，可以通过对三角图形方向调转，切换实心和空心，或对详情内容增加边框来提高辨识度，选取其中的一种或多种方案组合均可

**Comment by knowsex** [comment]
谢谢您的反馈，我们会根据您的反馈对页面做出调整优化。
感谢支持知性。
