### ISSUE TITLE
[Feature Request] 是否把轻触继续更改为点按按钮继续, 以防误触

### ISSUE THREAD

**Issue by Dynesshely** [knowsex/knowsex.github.io#4]
这个问题在PC上不容易出现  
但若当事人在公众场合使用手机浏览时, 容易出现手滑再次点击的情况, 造成社会性死亡  
所以建议修改为点击按钮继续, 同时尽量将按钮放置于屏幕上方

**Comment by knowsex** [comment]
感谢您的建议，我们会根据您的建议改进交互逻辑。

**Comment by knowsex** [comment]
网站已针对您的建议更新新的交互。由于主域名存在缓存，您可通过访问 https://knowsex.vercel.app/ 查看新的更改。
