### ISSUE TITLE
怀孕率的单位不合逻辑

### ISSUE THREAD

**Issue by RimoChan** [knowsex/knowsex.github.io#7]
![image](https://user-images.githubusercontent.com/20064807/162180000-db470296-bf40-4781-8ff7-2f2d43dce10b.png)

问题是，`有效性：每年每百名妇女坚持正确使用怀孕率`列，`0.1`、`0.3`等数值，是什么？

如果指每100人中期望的怀孕人数，那它的单位就不应该是`%`而是`1人`。
如果指每1个人中的怀孕率，那`每百名`就是误导的。

**Comment by knowsex** [comment]
好问题。
这个表格来自世界卫生组织的网站：https://www.who.int/zh/news-room/fact-sheets/detail/family-planning-contraception
这个`%`或许是当时的疏忽。
根据上下文语意，我认为或许是“怀孕次数”，但是我不是很能确定，我会再和小伙伴讨论一下。
感谢您提出这个问题。

**Comment by RimoChan** [comment]
原来如此……你把网站切到英文，表头是`pregnancies per 100 women per year with consistent and correct use`，的确是`每年每100个妇女正确使用怀孕了几次`。

**Comment by knowsex** [comment]
了然。稍后修改，非常感谢您的帮助 (。・∀・)ノ

**Comment by RimoChan** [comment]
![](https://user-images.githubusercontent.com/20064807/161945480-030ac8c2-c91f-4001-b9d8-c5cee658923a.png)

**Comment by knowsex** [comment]
已勘误。该页 CDN 缓存已清除，不过可能要稍后看到改变。
